title: Small Web
desciption: >
  A jekyll theme website.
email: lakillsama@gmail.com
baseurl: "/atlas-jekyll-theme"      # the subpath of your site, e.g. /blog
url: "https://lakillsama.github.io" # the base hostname & protocol for your site
twitter_username: lakillsama
github_username:  lakillsama
markdown: kramdown
page_excerpts: true
favicon: "/img/atlas.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
